# Generated by Django 5.1.4 on 2026-06-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_accepted',
            field=models.BooleanField(default=False, verbose_name='已同意隐私协议'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='同意时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_version',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='协议版本'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='执业编号'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', '普通用户'), ('counselor', '心理咨询师'), ('doctor', '医生')], db_index=True, default='patient', help_text='用户角色：普通用户/心理咨询师/医生', max_length=16, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='职称/机构'),
        ),
    ]
