# Generated by Django 4.2.9 on 2026-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='因子')),
                ('factor_name', models.CharField(max_length=50, verbose_name='因子名称')),
                ('mean', models.FloatField(verbose_name='全国常模均值')),
                ('std', models.FloatField(verbose_name='标准差')),
                ('description', models.TextField(blank=True, null=True, verbose_name='因子说明')),
            ],
            options={
                'verbose_name': '常模数据',
                'verbose_name_plural': '常模数据',
                'db_table': 'scl90_norm',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='题号')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('factor', models.CharField(choices=[('SOM', '躯体化'), ('O-C', '强迫症状'), ('I-S', '人际关系敏感'), ('DEP', '抑郁'), ('ANX', '焦虑'), ('HOS', '敌对'), ('PHOB', '恐怖'), ('PAR', '偏执'), ('PSY', '精神病性'), ('OTH', '其他')], db_index=True, max_length=10, verbose_name='因子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问卷题目',
                'verbose_name_plural': '问卷题目',
                'db_table': 'scl90_question',
                'ordering': ['number'],
            },
        ),
    ]
