# Generated by Django 5.1.4 on 2026-06-20 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PHQ9', 'PHQ-9 抑郁症筛查量表'), ('GAD7', 'GAD-7 广泛性焦虑量表')], db_index=True, max_length=16, unique=True, verbose_name='量表代码')),
                ('name', models.CharField(max_length=64, verbose_name='量表名称')),
                ('trigger_factor', models.CharField(blank=True, default='', help_text='当 SCL-90 该因子升高时建议追加此量表', max_length=10, verbose_name='触发因子')),
                ('description', models.TextField(blank=True, default='', verbose_name='量表说明')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='满分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '子量表',
                'verbose_name_plural': '子量表',
                'db_table': 'scl90_subscale',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubScaleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, verbose_name='题号')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.subscale', verbose_name='量表')),
            ],
            options={
                'verbose_name': '子量表题目',
                'verbose_name_plural': '子量表题目',
                'db_table': 'scl90_subscale_question',
                'ordering': ['number'],
                'unique_together': {('scale', 'number')},
            },
        ),
    ]
