# Generated by Django 4.2.9 on 2026-06-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_score', models.FloatField(default=0, verbose_name='躯体化因子分')),
                ('oc_score', models.FloatField(default=0, verbose_name='强迫症状因子分')),
                ('is_score', models.FloatField(default=0, verbose_name='人际关系敏感因子分')),
                ('dep_score', models.FloatField(default=0, verbose_name='抑郁因子分')),
                ('anx_score', models.FloatField(default=0, verbose_name='焦虑因子分')),
                ('hos_score', models.FloatField(default=0, verbose_name='敌对因子分')),
                ('phob_score', models.FloatField(default=0, verbose_name='恐怖因子分')),
                ('par_score', models.FloatField(default=0, verbose_name='偏执因子分')),
                ('psy_score', models.FloatField(default=0, verbose_name='精神病性因子分')),
                ('oth_score', models.FloatField(default=0, verbose_name='其他因子分')),
                ('gsi', models.FloatField(default=0, verbose_name='总症状指数(GSI)')),
                ('positive_count', models.IntegerField(default=0, verbose_name='阳性项目数')),
                ('positive_avg', models.FloatField(default=0, verbose_name='阳性症状均分')),
                ('total_sum', models.IntegerField(default=0, verbose_name='总分')),
                ('overall_risk', models.CharField(choices=[('green', '正常（绿）'), ('yellow', '轻度（黄）'), ('red', '中度及以上（红）')], default='green', max_length=10, verbose_name='整体风险等级')),
                ('answers_json', models.JSONField(default=dict, verbose_name='答案详情')),
                ('factors_detail', models.JSONField(default=dict, verbose_name='因子与常模对比详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='测评时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '测评记录',
                'verbose_name_plural': '测评记录',
                'db_table': 'scl90_assessment_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
