# Generated by Django 5.1.4 on 2026-06-20 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrecord',
            name='answered_count',
            field=models.IntegerField(default=90, verbose_name='作答题数'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='mode',
            field=models.CharField(choices=[('classic', '经典90题'), ('adaptive', '自适应')], default='classic', max_length=16, verbose_name='测评模式'),
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('classic', '经典90题'), ('adaptive', '自适应')], default='classic', max_length=16, verbose_name='测评模式')),
                ('screening_items_count', models.IntegerField(default=0, verbose_name='筛查题数')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '测评会话',
                'verbose_name_plural': '测评会话',
                'db_table': 'scl90_assessment_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='records.assessmentsession', verbose_name='所属会话'),
        ),
        migrations.CreateModel(
            name='FollowUpNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='备注内容')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='随访日期')),
                ('follow_up_type', models.CharField(blank=True, default='', max_length=24, verbose_name='随访方式')),
                ('next_action', models.CharField(blank=True, default='', max_length=255, verbose_name='下一步计划')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_notes_received', to=settings.AUTH_USER_MODEL, verbose_name='患者')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_notes_written', to=settings.AUTH_USER_MODEL, verbose_name='专业人员')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_notes', to='records.assessmentrecord', verbose_name='关联测评记录')),
            ],
            options={
                'verbose_name': '随访备注',
                'verbose_name_plural': '随访备注',
                'db_table': 'scl90_followup_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubScaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_code', models.CharField(db_index=True, max_length=16, verbose_name='量表代码')),
                ('scale_name', models.CharField(blank=True, default='', max_length=64, verbose_name='量表名称')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('max_score', models.IntegerField(default=0, verbose_name='满分')),
                ('severity', models.CharField(blank=True, default='', max_length=24, verbose_name='严重度')),
                ('severity_label', models.CharField(blank=True, default='', max_length=32, verbose_name='严重度标签')),
                ('advice', models.TextField(blank=True, default='', verbose_name='建议')),
                ('answers_json', models.JSONField(default=dict, verbose_name='答案详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscale_records', to='records.assessmentrecord', verbose_name='关联测评记录')),
            ],
            options={
                'verbose_name': '子量表记录',
                'verbose_name_plural': '子量表记录',
                'db_table': 'scl90_subscale_record',
                'ordering': ['scale_code'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='分配备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='患者')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_professional', to=settings.AUTH_USER_MODEL, verbose_name='专业人员')),
            ],
            options={
                'verbose_name': '医患分配',
                'verbose_name_plural': '医患分配',
                'db_table': 'scl90_patient_assignment',
                'ordering': ['-created_at'],
                'unique_together': {('patient', 'professional')},
            },
        ),
    ]
