# Generated by Django 5.1.4 on 2026-06-20 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('export', '导出'), ('login', '登录'), ('logout', '登出')], max_length=16, verbose_name='操作类型')),
                ('resource_type', models.CharField(blank=True, default='', max_length=64, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=64, verbose_name='资源ID')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'db_table': 'scl90_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy', '隐私协议'), ('assessment', '测评数据收集'), ('share_professional', '共享给专业人员')], default='privacy', max_length=24, verbose_name='同意类型')),
                ('version', models.CharField(max_length=16, verbose_name='协议版本')),
                ('accepted', models.BooleanField(default=False, verbose_name='是否同意')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '同意授权记录',
                'verbose_name_plural': '同意授权记录',
                'db_table': 'scl90_consent_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
